# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Korekurver
                                 A QGIS plugin
 Med Kørekurver kan der vises kørekurver på et kort.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-02
        copyright            : (C) 2022 by Nordiq Group
        email                : stb@nordiq-group.dk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Korekurver class from file Korekurver.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .korekurver import Korekurver
    return Korekurver(iface)
